/*ALTER TABLE [BookAuthor] DROP CONSTRAINT FK_Author_BookId;
ALTER TABLE [BookAuthor] DROP CONSTRAINT FK_Author_AuthorId;
ALTER TABLE [BookLanguage] DROP CONSTRAINT FK_BookLanguage_BookId;
ALTER TABLE [BookLanguage] DROP CONSTRAINT FK_BookLanguage_LanguageId;
ALTER TABLE [BookGenre] DROP CONSTRAINT FK_BookGenre_BookId;
ALTER TABLE [BookGenre] DROP CONSTRAINT FK_BookGenre_GenreId;
ALTER TABLE [BookReview] DROP CONSTRAINT FK_BookReview_ReviewId;
ALTER TABLE [BookReview] DROP CONSTRAINT FK_BookReview_bookId;
ALTER TABLE [Review] DROP CONSTRAINT FK_Review_BookId;
ALTER TABLE [Review] DROP CONSTRAINT FK_Review_UserId;
ALTER TABLE [Feedback] DROP CONSTRAINT FK_Feedback_OrderId;
ALTER TABLE [Feedback] DROP CONSTRAINT FK_Feedback_UserId;
ALTER TABLE [OrderBooklist] DROP CONSTRAINT FK_OrderBooklist_OrderId;
ALTER TABLE [OrderBooklist] DROP CONSTRAINT FK_OrderBooklist_BookId;
ALTER TABLE [OwnedBook] DROP CONSTRAINT FK_OwnedBook_BookId;
ALTER TABLE [OwnedBook] DROP CONSTRAINT FK_OwnedBook_UserId;
ALTER TABLE [UserBilling] DROP CONSTRAINT FK_Billing_OrderId;
ALTER TABLE [UserBilling] DROP CONSTRAINT FK_Billing_UserId;
ALTER TABLE [Orders] DROP CONSTRAINT FK_Order_ShippingAddressId;
ALTER TABLE [Orders] DROP CONSTRAINT FK_Orders_BillingAddressId;
ALTER TABLE [Orders] DROP CONSTRAINT FK_Order_CardId;
ALTER TABLE [UserCard] DROP CONSTRAINT FK_UserCard_cardDetailsId;
ALTER TABLE [UserCard] DROP CONSTRAINT FK_UserCard_UserId;
ALTER TABLE [UserPayment] DROP CONSTRAINT FK_UserPayment_PaymentId;
ALTER TABLE [UserPayment] DROP CONSTRAINT FK_UserPayment_UserId;
ALTER TABLE [UserReadBook] DROP CONSTRAINT FK_UserReadBook_BookId;
ALTER TABLE [UserReadBook] DROP CONSTRAINT FK_UserReadBook_UserId;
ALTER TABLE [UserReview] DROP CONSTRAINT FK_UserReview_ReviewId;
ALTER TABLE [UserReview] DROP CONSTRAINT FK_UserReview_UserId;
ALTER TABLE [UserShipping] DROP CONSTRAINT FK_UserShipping_ShippingId;
ALTER TABLE [UserShipping] DROP CONSTRAINT FK_UserShipping_UserId;
ALTER TABLE [Wishlist] DROP CONSTRAINT FK_Wishlist_BookId;
ALTER TABLE [Wishlist] DROP CONSTRAINT FK_Wishlist_UserId;
ALTER TABLE [Book] DROP CONSTRAINT FK_Book_PublisherId;
ALTER TABLE [Book] DROP CONSTRAINT FK_Book_FormatId;
ALTER TABLE [Address] DROP CONSTRAINT FK_Address_CountryId;
ALTER TABLE [UserAccount] DROP CONSTRAINT FK_UserAccount_FavoriteBookId;
ALTER TABLE [UserAccount] DROP CONSTRAINT FK_UserAccount_FavoriteAuthorId;
ALTER TABLE [BookAuthor] DROP CONSTRAINT FK_BookAuthor_AuthorId;
ALTER TABLE [BookAuthor] DROP CONSTRAINT FK_BookAuthor_BookId;

drop table [Address];
drop table Author;
drop table Book;
drop table BookAuthor;
drop table BookGenre;
drop table BookLanguage;
drop table BookReview;
drop table CardDetails;
drop table Country;
drop table Feedback;
drop table [Format];
drop table Genre;
drop table [Language];
drop table OrderBooklist;
drop table Orders;
drop table OwnedBook;
drop table Publisher;
drop table Review;
drop table UserAccount;
drop table UserBilling;
drop table UserCard;
drop table UserPayment;
drop table UserReadBook;
drop table UserReview;
drop table UserShipping;
drop table Wishlist;
*/